const ISO3_TO_ISO2: Record<string, string> = {
  "ALG": "dz",
  "ARG": "ar",
  "AUS": "au",
  "AUT": "at",
  "BEL": "be",
  "BIH": "ba",
  "BRA": "br",
  "CAN": "ca",
  "CIV": "ci",
  "COL": "co",
  "COD": "cd",
  "CPV": "cv",
  "CRO": "hr",
  "CUW": "cw",
  "CZE": "cz",
  "DEN": "dk",
  "ECU": "ec",
  "EGY": "eg",
  "ENG": "gb-eng",
  "ESP": "es",
  "FRA": "fr",
  "GER": "de",
  "GHA": "gh",
  "HTI": "ht",
  "ITA": "it",
  "JPN": "jp",
  "JOR": "jo",
  "KOR": "kr",
  "MAR": "ma",
  "MEX": "mx",
  "NED": "nl",
  "NOR": "no",
  "NZL": "nz",
  "PAN": "pa",
  "PAR": "py",
  "PER": "pe",
  "POR": "pt",
  "QAT": "qa",
  "RSA": "za",
  "KSA": "sa",
  "SCO": "gb-sct",
  "SEN": "sn",
  "SUI": "ch",
  "SWE": "se",
  "TUN": "tn",
  "TUR": "tr",
  "URU": "uy",
  "USA": "us",
  "UZB": "uz",
  "WAL": "gb-wls",
};

export function getCountryFlagUrl(teamId: string): string {
  const code = ISO3_TO_ISO2[teamId.toUpperCase()];
  if (!code) {
    return `https://flagcdn.com/w40/un.png`;
  }
  return `https://flagcdn.com/w40/${code}.png`;
}
